### ISSUE TITLE
Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

### ISSUE THREAD

**Issue by ghost** [UKHomeOffice/docker-zookeeper#1]
hi, when I follow your step and I got the error when I did the Test the Cluster
`[root@master kube]# kubectl exec -ti zookeeper-1-4npc6 bash

[root@zookeeper-1-4npc6 zookeeper]# bin/zkCli.sh 

/usr/bin/java

Connecting to localhost:2181

2017-02-13 09:01:55,349 [myid:] - INFO  [main:Environment@109] - Client environment:zookeeper.version=3.5.1-alpha-1693007, built on 07/28/2015 07:19 GMT

2017-02-13 09:01:55,355 [myid:] - INFO  [main:Environment@109] - Client environment:host.name=zookeeper-1-4npc6

2017-02-13 09:01:55,355 [myid:] - INFO  [main:Environment@109] - Client environment:java.version=1.8.0_71

2017-02-13 09:01:55,359 [myid:] - INFO  [main:Environment@109] - Client environment:java.vendor=Oracle Corporation

2017-02-13 09:01:55,359 [myid:] - INFO  [main:Environment@109] - Client environment:java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.71-2.b15.el7_2.x86_64/jre

2017-02-13 09:01:55,359 [myid:] - INFO  [main:Environment@109] - Client environment:java.class.path=/zookeeper/bin/../build/classes:/zookeeper/bin/../build/lib/*.jar:/zookeeper/bin/../lib/slf4j-log4j12-1.7.5.jar:/zookeeper/bin/../lib/slf4j-api-1.7.5.jar:/zookeeper/bin/../lib/servlet-api-2.5-20081211.jar:/zookeeper/bin/../lib/netty-3.7.0.Final.jar:/zookeeper/bin/../lib/log4j-1.2.16.jar:/zookeeper/bin/../lib/jline-2.11.jar:/zookeeper/bin/../lib/jetty-util-6.1.26.jar:/zookeeper/bin/../lib/jetty-6.1.26.jar:/zookeeper/bin/../lib/javacc.jar:/zookeeper/bin/../lib/jackson-mapper-asl-1.9.11.jar:/zookeeper/bin/../lib/jackson-core-asl-1.9.11.jar:/zookeeper/bin/../lib/commons-cli-1.2.jar:/zookeeper/bin/../zookeeper-3.5.1-alpha.jar:/zookeeper/bin/../src/java/lib/*.jar:/zookeeper/bin/../conf:

2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib

2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:java.io.tmpdir=/tmp

2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:java.compiler=<NA>

2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:os.name=Linux
2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:os.arch=amd64
2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:os.version=3.10.0-327.el7.x86_64
2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:user.name=root
2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:user.home=/root
2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:user.dir=/zookeeper
2017-02-13 09:01:55,360 [myid:] - INFO  [main:Environment@109] - Client environment:os.memory.free=11MB
2017-02-13 09:01:55,370 [myid:] - INFO  [main:Environment@109] - Client environment:os.memory.max=247MB
2017-02-13 09:01:55,370 [myid:] - INFO  [main:Environment@109] - Client environment:os.memory.total=15MB
2017-02-13 09:01:55,389 [myid:] - INFO  [main:ZooKeeper@716] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@28ba21f3
Welcome to ZooKeeper!
2017-02-13 09:01:55,498 [myid:] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1138] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
JLine support is enabled
2017-02-13 09:01:55,762 [myid:] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1257] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:355)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1236)
[zk: localhost:2181(CONNECTING) 0] 2017-02-13 09:01:55,885 [myid:] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1138] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
2017-02-13 09:01:55,886 [myid:] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1257] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:355)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1236)
2017-02-13 09:01:57,015 [myid:] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1138] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)`

and here are my deployment:
![image](https://cloud.githubusercontent.com/assets/24426986/22868380/43e1f9fe-f1d0-11e6-9e5a-63e218c43397.png)

![image](https://cloud.githubusercontent.com/assets/24426986/22868384/518b4240-f1d0-11e6-9d77-12bfd2afd010.png)

can you tell me how can I fix it? thanks

ps: I am working on vmware and one master with three nodes

**Comment by ok-he** [comment]
when I did the following steps
[root@master kube]# kubectl exec -ti zookeeper-1-4npc6 bash
[root@zookeeper-1-4npc6 zookeeper]# bin/zkCli.sh

![image](https://cloud.githubusercontent.com/assets/24426986/22868414/a57c824c-f1d0-11e6-8f35-9d0518917e0d.png)

**Comment by ok-he** [comment]
and when I did the 
[root@master kube]# kubectl logs zookeeper-1-4npc6
shows

![image](https://cloud.githubusercontent.com/assets/24426986/22868477/7a71c94e-f1d1-11e6-9be7-e2866a85e54b.png)

**Comment by chenxuan199206** [comment]
i also meet the problem,can you tell me how did resolve it

**Comment by TrillStones** [comment]
maybe you connect to wrong server with ip address.

**Comment by thesixonenine** [comment]
i also meet the problem,can you tell me how can I fix it?

**Comment by the-c0d3r** [comment]
@thesixonenine Connection refused usually mean the port is closed. Make sure you are connecting to the correct port and correct ip. And check if the zookeeper server is up.

**Comment by sayak1711** [comment]
This error sometimes happens when someone has started zookeper or kafka as root user and some log files have been created which can't be accessed when other user starts it. So we have to delete all log files, then start again. In kafka log files are present in logs and kafka_logs
sudo rm -rf logs
sudo rm -rf kafka_logs
